apiVersion: v1
name: quarks-job
version: x.x.x
appVersion: x.x.x
description: A Helm chart for quarks-job, a k8s operator for quarks jobs
home: https://github.com/cloudfoundry-incubator/quarks-job
icon: https://cloudfoundry-incubator.github.io/quarks-helm/logo.png
keywords:
- quarks
- job
- output
sources:
- https://github.com/cloudfoundry-incubator/quarks-job
- https://github.com/cfcontainerizationbot/cf-operator-base
maintainers:
- name: project-quarks
  email: project-quarks@googlegroups.com
