name-template: '$PREVIOUS_TAG 🌈'
tag-template: '$PREVIOUS_TAG'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    label: 'chore'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
template: |

  * https://hub.helm.sh/charts/quarks/quarks-job
  * https://hub.docker.com/r/cfcontainerization/quarks-job/tags

  ## Changes

  $CHANGES
