apiVersion: fissile.cloudfoundry.org/v1alpha1
kind: ExtendedJob
metadata:
  name: one-time-sleep
spec:
  template:
    spec:
      backoffLimit: 2
      template:
        spec:
          containers:
          - command:
            - sleep
            - "15"
            image: busybox
            name: busybox
          restartPolicy: Never
          terminationGracePeriodSeconds: 1
  trigger:
    strategy: once
