apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: ExtendedJob
metadata:
  name: manual-sleep
spec:
  template:
    backoffLimit: 2
    spec:
      template:
        spec:
          containers:
          - command:
            - sleep
            - "15"
            image: busybox
            name: busybox
          restartPolicy: Never
          terminationGracePeriodSeconds: 1
  trigger:
    strategy: now
