---
apiVersion: v1
data:
  keyA: valueAUpdated
  keyB: valueB
kind: ConfigMap
metadata:
  name: config1
---
apiVersion: v1
stringData:
  keyA: dmFsdWUx
  keyB: dmFsdWUy
kind: Secret
type: Opaque
metadata:
  name: secret1
---
apiVersion: fissile.cloudfoundry.org/v1alpha1
kind: ExtendedJob
metadata:
  name: auto-errand-sleep-again
spec:
  template:
    spec:
      volumes:
      - name: secret-volume
        secret:
          secretName: secret1
      containers:
      - command:
        - sleep
        - "15"
        image: busybox
        name: busybox
        volumeMounts:
          - name: secret-volume
            readOnly: true
            mountPath: "/etc/secret-volume"
        env:
          - name: SPECIAL_KEY
            valueFrom:
              configMapKeyRef:
                name: config1
                key: keyA

      restartPolicy: Never
      terminationGracePeriodSeconds: 1
  trigger:
    strategy: once
  updateOnConfigChange: true
