apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: QuarksJob
metadata:
  name: myfoo
spec:
  template:
    backoffLimit: 2
    spec:
      template:
        spec:
          containers:
            - name: jsonout
              image: busybox
              command: ["/bin/sh"]
              args: ["-c","json='{\"foo\": \"1\", \"bar\": \"baz\"}' && sleep 5 && echo $json >> /mnt/quarks/output.json"]
          restartPolicy: Never
          terminationGracePeriodSeconds: 1
  trigger:
    strategy: once
  output:
    outputMap:
      jsonout:
        output.json:
          name: foo-json
          versioned: false
    secretLabels:
      key: value
