apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: QuarksJob
metadata:
  name: deletes-pod-1
spec:
  template:
    backoffLimit: 2
    spec:
      template:
        metadata:
          labels:
            delete: pod
        spec:
          containers:
          - command:
            - sleep
            - "5"
            image: busybox
            name: busybox
          restartPolicy: Never
          terminationGracePeriodSeconds: 1
  trigger:
    strategy: once
