/*

Don't alter this file, it was generated.

*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "code.cloudfoundry.org/quarks-job/pkg/kube/client/clientset/versioned/typed/quarksjob/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeQuarksjobV1alpha1 struct {
	*testing.Fake
}

func (c *FakeQuarksjobV1alpha1) QuarksJobs(namespace string) v1alpha1.QuarksJobInterface {
	return &FakeQuarksJobs{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeQuarksjobV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
