/*

Don't alter this file, it was generated.

*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "code.cloudfoundry.org/quarks-job/pkg/kube/apis/quarksjob/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeQuarksJobs implements QuarksJobInterface
type FakeQuarksJobs struct {
	Fake *FakeQuarksjobV1alpha1
	ns   string
}

var quarksjobsResource = schema.GroupVersionResource{Group: "quarksjob", Version: "v1alpha1", Resource: "quarksjobs"}

var quarksjobsKind = schema.GroupVersionKind{Group: "quarksjob", Version: "v1alpha1", Kind: "QuarksJob"}

// Get takes name of the quarksJob, and returns the corresponding quarksJob object, and an error if there is any.
func (c *FakeQuarksJobs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.QuarksJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(quarksjobsResource, c.ns, name), &v1alpha1.QuarksJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.QuarksJob), err
}

// List takes label and field selectors, and returns the list of QuarksJobs that match those selectors.
func (c *FakeQuarksJobs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.QuarksJobList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(quarksjobsResource, quarksjobsKind, c.ns, opts), &v1alpha1.QuarksJobList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.QuarksJobList{ListMeta: obj.(*v1alpha1.QuarksJobList).ListMeta}
	for _, item := range obj.(*v1alpha1.QuarksJobList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested quarksJobs.
func (c *FakeQuarksJobs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(quarksjobsResource, c.ns, opts))

}

// Create takes the representation of a quarksJob and creates it.  Returns the server's representation of the quarksJob, and an error, if there is any.
func (c *FakeQuarksJobs) Create(ctx context.Context, quarksJob *v1alpha1.QuarksJob, opts v1.CreateOptions) (result *v1alpha1.QuarksJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(quarksjobsResource, c.ns, quarksJob), &v1alpha1.QuarksJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.QuarksJob), err
}

// Update takes the representation of a quarksJob and updates it. Returns the server's representation of the quarksJob, and an error, if there is any.
func (c *FakeQuarksJobs) Update(ctx context.Context, quarksJob *v1alpha1.QuarksJob, opts v1.UpdateOptions) (result *v1alpha1.QuarksJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(quarksjobsResource, c.ns, quarksJob), &v1alpha1.QuarksJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.QuarksJob), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeQuarksJobs) UpdateStatus(ctx context.Context, quarksJob *v1alpha1.QuarksJob, opts v1.UpdateOptions) (*v1alpha1.QuarksJob, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(quarksjobsResource, "status", c.ns, quarksJob), &v1alpha1.QuarksJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.QuarksJob), err
}

// Delete takes name of the quarksJob and deletes it. Returns an error if one occurs.
func (c *FakeQuarksJobs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(quarksjobsResource, c.ns, name), &v1alpha1.QuarksJob{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeQuarksJobs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(quarksjobsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.QuarksJobList{})
	return err
}

// Patch applies the patch and returns the patched quarksJob.
func (c *FakeQuarksJobs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.QuarksJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(quarksjobsResource, c.ns, name, pt, data, subresources...), &v1alpha1.QuarksJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.QuarksJob), err
}
