{{- if .Values.singleNamespace.create }}

---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.singleNamespace.name }}
  labels:
    quarks.cloudfoundry.org/qjob-namespace: true
    quarks.cloudfoundry.org/qjob-service-account: quarks-job-persist-output

{{- if .Values.global.rbac.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: quarks-job-persist-output
  namespace: {{ .Values.singleNamespace.name }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: quarks-job-persist-output
  namespace: {{ .Values.singleNamespace.name }}
subjects:
- kind: ServiceAccount
  name: quarks-job-persist-output
roleRef:
  kind: ClusterRole
  name: quarks-job-persist-output
  apiGroup: rbac.authorization.k8s.io
{{- end }}

{{- end }}

