/*

Don't alter this file, it was generated.

*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// QuarksJobListerExpansion allows custom methods to be added to
// QuarksJobLister.
type QuarksJobListerExpansion interface{}

// QuarksJobNamespaceListerExpansion allows custom methods to be added to
// QuarksJobNamespaceLister.
type QuarksJobNamespaceListerExpansion interface{}
