name: quarks-job-ci

on: [push, pull_request]
      
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        go_version: ["1.13.4"]
          
    steps:
    - name: Set up Go ${{matrix.go_version}} 
      uses: actions/setup-go@v2
      with:
        go-version: ${{matrix.go_version}}
    - uses: actions/checkout@v2
    - name: lint
      run: |
        curl -LO https://github.com/dominikh/go-tools/releases/download/2020.1.3/staticcheck_linux_amd64.tar.gz
        sudo tar xfz staticcheck_linux_amd64.tar.gz --strip-component 1 -C $GOPATH/bin staticcheck/staticcheck
        go get -u golang.org/x/lint/golint
        make lint

  unit-tests:
    needs: [lint]
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        go_version: ["1.13.4"]
          
    steps:
    - name: Set up Go ${{matrix.go_version}} 
      uses: actions/setup-go@v2
      with:
        go-version: ${{matrix.go_version}}
    - uses: actions/checkout@v2
    - name: Run unit tests
      run: make test-unit

