name: quarks-job-publish

on:
  push:
    branches-ignore:
    - refs/tags/*

env:
  PROJECT: quarks-job
  DOCKER_IMAGE_ORG: ghcr.io/cloudfoundry-incubator
  DOCKER_IMAGE_REPOSITORY: quarks-operator

jobs:
  publish:
    runs-on: ubuntu-latest

    if: github.repository == 'cloudfoundry-incubator/quarks-job'
    steps:
    - uses: azure/setup-helm@v1
      with:
        version: v3.0.0
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install shared tools
      run: |
        bin/tools
    - name: Prepare ARTIFACT_VERSION env
      shell: bash
      run: |
        git fetch --unshallow
        GITHUB_ACTION_BRANCH=${GITHUB_REF#refs/heads/}
        . bin/include/versioning
        echo "##[set-output name=version;]$(echo $ARTIFACT_VERSION"
      id: prepare_version_env

    - name: Vendor go mod dependencies
      run: go mod vendor
    - name: Publish Docker Image
      uses: whoan/docker-build-with-cache-action@v5
      with:
        username: cfcontainerizationbot
        password: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
        registry: "${{ env.DOCKER_IMAGE_ORG }}"
        image_name: "${{ env.DOCKER_IMAGE_REPOSITORY }}"
        image_tag: "${{ steps.prepare_version_env.outputs.version }}"

    - name: Build Helm Chart
      run: |
        echo "Publish Helm Chart for $ARTIFACT_VERSION"
        cp -r "deploy/helm" "helm"
        perl -pi -e "s|repository: .*|repository: $DOCKER_IMAGE_REPOSITORY|g" "helm/$PROJECT/values.yaml"
        perl -pi -e "s|org: .*|org: $DOCKER_IMAGE_ORG|g" "helm/$PROJECT/values.yaml"
        perl -pi -e "s|tag: .*|tag: $ARTIFACT_VERSION|g" "helm/$PROJECT/values.yaml"

        # helm compatible version string
        version=$(echo "$ARTIFACT_VERSION" | sed 's/^v//')
        helm package "helm/$PROJECT" \
          --app-version "$version" \
          --version "$version" \
          --destination "helm"
      env:
        ARTIFACT_VERSION: "${{ steps.prepare_version_env.outputs.version }}"

    - name: Publish Helm Chart
      run: |
        base_url="https://CFContainerizationBot:$GH_PASSWORD@github.com/cloudfoundry-incubator"
        git clone "$base_url/quarks-helm.git" ./updated/ && \
          bin/publish-helm-repo

        echo "Tag Github Commit with $ARTIFACT_VERSION"
        git tag -a "$ARTIFACT_VERSION" -m "tag $ARTIFACT_VERSION"
        git push --quiet "$base_url/$PROJECT.git" "$ARTIFACT_VERSION"
      env:
        # for git push to helm repo
        GH_PASSWORD: "${{ secrets.GH_PASSWORD }}"
        ARTIFACT_VERSION: "${{ steps.prepare_version_env.outputs.version }}"
