name: Release Drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    tags:
      - 'v1.*'

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Get current tag
        id: get_tag
        run: echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}

      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: release-drafter/release-drafter@v5
        with:
          name: "${{ steps.get_tag.outputs.TAG }} 🌈"
          tag: ${{ steps.get_tag.outputs.TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
